//! Typed data structures generated from a template's data contract
//! ([`crate::validate::contract_schema`]), so a test station builds exactly the
//! data the template reads instead of matching field names by hand.

use serde_json::Value;
use std::fmt::Write;

/// Languages [`typedefs`] can write.
pub const LANGUAGES: &[&str] = &["csharp", "python", "typescript", "labview"];

fn pascal(s: &str) -> String {
    let mut out = String::new();
    let mut up = true;
    for c in s.chars() {
        if c.is_alphanumeric() {
            if up {
                out.extend(c.to_uppercase());
            } else {
                out.push(c);
            }
            up = false;
        } else {
            up = true;
        }
    }
    if out.is_empty() || out.starts_with(|c: char| c.is_ascii_digit()) {
        out.insert(0, 'F');
    }
    out
}

/// Singular-ish type name for list items: `measurements` → `Measurement`.
fn item_name(field: &str) -> String {
    let p = pascal(field);
    if let Some(s) = p.strip_suffix("ies") {
        format!("{s}y")
    } else if p.ends_with("ss") {
        p
    } else if let Some(s) = p.strip_suffix('s') {
        s.to_string()
    } else {
        format!("{p}Item")
    }
}

/// A flattened type: name and fields (name, type, required).
struct Struct {
    name: String,
    fields: Vec<(String, Ty, bool)>,
}

enum Ty {
    Str,
    Num,
    Bool,
    Any,
    Obj(String),
    List(Box<Ty>),
}

fn collect(schema: &Value, name: &str, out: &mut Vec<Struct>) -> Ty {
    match schema.get("type").and_then(Value::as_str) {
        Some("object") => {
            let required: Vec<&str> = schema
                .get("required")
                .and_then(Value::as_array)
                .map(|a| a.iter().filter_map(Value::as_str).collect())
                .unwrap_or_default();
            let mut fields = Vec::new();
            if let Some(props) = schema.get("properties").and_then(Value::as_object) {
                for (k, v) in props {
                    let child = match v.get("type").and_then(Value::as_str) {
                        Some("array") => item_name(k),
                        _ => pascal(k),
                    };
                    let ty = collect(v, &child, out);
                    fields.push((k.clone(), ty, required.contains(&k.as_str())));
                }
            }
            // Children first is fine for every target; keep the root last so it reads top-down reversed.
            out.push(Struct { name: name.to_string(), fields });
            Ty::Obj(name.to_string())
        }
        Some("array") => {
            let items = schema.get("items").cloned().unwrap_or(Value::Null);
            Ty::List(Box::new(collect(&items, name, out)))
        }
        Some("string") => Ty::Str,
        Some("number") | Some("integer") => Ty::Num,
        Some("boolean") => Ty::Bool,
        _ => Ty::Any,
    }
}

fn ty_cs(t: &Ty) -> String {
    match t {
        Ty::Str => "string".into(),
        Ty::Num => "double?".into(),
        Ty::Bool => "bool?".into(),
        Ty::Any => "object".into(),
        Ty::Obj(n) => n.clone(),
        Ty::List(i) => format!("List<{}>", ty_cs(i)),
    }
}

fn ty_py(t: &Ty) -> String {
    match t {
        Ty::Str => "str".into(),
        Ty::Num => "float".into(),
        Ty::Bool => "bool".into(),
        Ty::Any => "Any".into(),
        Ty::Obj(n) => format!("\"{n}\""),
        Ty::List(i) => format!("list[{}]", ty_py(i)),
    }
}

fn ty_ts(t: &Ty) -> String {
    match t {
        Ty::Str => "string".into(),
        Ty::Num => "number".into(),
        Ty::Bool => "boolean".into(),
        Ty::Any => "unknown".into(),
        Ty::Obj(n) => n.clone(),
        Ty::List(i) => format!("{}[]", ty_ts(i)),
    }
}

fn ty_lv(t: &Ty) -> String {
    match t {
        Ty::Str => "String".into(),
        Ty::Num => "DBL (NaN when not measured)".into(),
        Ty::Bool => "Boolean".into(),
        Ty::Any => "String or DBL (type not known from the sample data)".into(),
        Ty::Obj(n) => format!("Cluster {n}"),
        Ty::List(i) => format!("1D Array of {}", ty_lv(i)),
    }
}

/// Generate typed structures for a contract schema. `root` names the top-level type.
pub fn typedefs(schema: &Value, lang: &str, root: &str) -> Result<String, String> {
    let mut structs = Vec::new();
    let root = pascal(if root.trim().is_empty() { "ReportData" } else { root });
    collect(schema, &root, &mut structs);
    let mut s = String::new();
    match lang {
        "csharp" => {
            s.push_str("// Generated by Report Builder from the template's data contract.\n");
            s.push_str("// Serialize with System.Text.Json: JsonSerializer.Serialize(data)\n");
            s.push_str("using System.Collections.Generic;\nusing System.Text.Json.Serialization;\n\n");
            for st in structs.iter().rev() {
                let _ = writeln!(s, "public class {}\n{{", st.name);
                for (k, t, req) in &st.fields {
                    let _ = writeln!(s, "    [JsonPropertyName(\"{k}\")]");
                    let opt = if *req { "" } else { " // optional" };
                    let _ = writeln!(s, "    public {} {} {{ get; set; }}{opt}", ty_cs(t), pascal(k));
                }
                s.push_str("}\n\n");
            }
        }
        "python" => {
            s.push_str("# Generated by Report Builder from the template's data contract.\n");
            s.push_str("# Build the data with these TypedDicts and pass it to ReportBuilder.render().\n");
            s.push_str("from typing import Any, NotRequired, TypedDict\n\n");
            for st in structs.iter() {
                let _ = writeln!(s, "\nclass {}(TypedDict):", st.name);
                if st.fields.is_empty() {
                    s.push_str("    pass\n");
                }
                for (k, t, req) in &st.fields {
                    let ty = if *req { ty_py(t) } else { format!("NotRequired[{}]", ty_py(t)) };
                    let _ = writeln!(s, "    {k}: {ty}");
                }
            }
        }
        "typescript" => {
            s.push_str("// Generated by Report Builder from the template's data contract.\n");
            for st in structs.iter().rev() {
                let _ = writeln!(s, "\nexport interface {} {{", st.name);
                for (k, t, req) in &st.fields {
                    let _ = writeln!(s, "  {}{}: {}", k, if *req { "" } else { "?" }, ty_ts(t));
                }
                s.push_str("}\n");
            }
        }
        "labview" => {
            s.push_str("Report Builder data contract: build this cluster, then Flatten To JSON.\n");
            s.push_str("Control labels must match the names below exactly (they are the JSON keys).\n\n");
            fn tree(structs: &[Struct], name: &str, depth: usize, s: &mut String) {
                let Some(st) = structs.iter().find(|x| x.name == name) else { return };
                for (k, t, req) in &st.fields {
                    let pad = "    ".repeat(depth);
                    let opt = if *req { "" } else { "   (optional)" };
                    let _ = writeln!(s, "{pad}{k}: {}{opt}", ty_lv(t));
                    let mut inner = t;
                    while let Ty::List(i) = inner {
                        inner = i;
                    }
                    if let Ty::Obj(n) = inner {
                        tree(structs, n, depth + 1, s);
                    }
                }
            }
            let _ = writeln!(s, "Cluster {root}");
            tree(&structs, &root, 1, &mut s);
            s.push_str("\nTimestamps: send an ISO 8601 string (Format Date/Time String with %Y-%m-%dT%H:%M:%S%z),\n");
            s.push_str("or the LabVIEW timestamp as a DBL; both are understood.\n");
        }
        other => return Err(format!("unknown language '{other}'; use one of {}", LANGUAGES.join(", "))),
    }
    Ok(s.trim_end().to_string() + "\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn schema() -> Value {
        json!({"type": "object", "required": ["dut", "measurements"], "properties": {
            "dut": {"type": "object", "required": ["serial"], "properties": {"serial": {"type": "string"}}},
            "measurements": {"type": "array", "items": {"type": "object", "required": ["value"], "properties": {
                "value": {"type": "number"}, "unit": {"type": "string"}
            }}}
        }})
    }

    #[test]
    fn every_language() {
        let cs = typedefs(&schema(), "csharp", "Final test").unwrap();
        assert!(cs.contains("public class FinalTest"));
        assert!(cs.contains("public List<Measurement> Measurements"));
        assert!(cs.contains("public double? Value"));
        let py = typedefs(&schema(), "python", "").unwrap();
        assert!(py.contains("class Measurement(TypedDict):"));
        assert!(py.contains("unit: NotRequired[str]"));
        let ts = typedefs(&schema(), "typescript", "").unwrap();
        assert!(ts.contains("measurements: Measurement[]"));
        let lv = typedefs(&schema(), "labview", "").unwrap();
        assert!(lv.contains("measurements: 1D Array of Cluster Measurement"));
        assert!(lv.contains("        value: DBL"));
        assert!(typedefs(&schema(), "cobol", "").is_err());
    }
}
