[package]
name = "report-builder-desktop"
description = "Report Builder desktop app"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "report_builder_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
reportcore = { path = "../../engine/reportcore" }
serde.workspace = true
serde_json.workspace = true
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
